language: php
php:
    - '7.0'

services:
    - postgresql

install:
    - cp app/config/parameters.yml app/config/parameters.yml.travis
    - composer install --dev
    - php bin/console doctrine:database:create
    - php bin/console doctrine:schema:update --force

script: phpunit --coverage-text

notifications:
    email:
        - t.leguen@cs2i-lorient.fr
