app:
    resource: "@AppBundle/Controller/"
    type:     annotation

users:
    type:     rest
    resource: AppBundle\Controller\UserController

auth-tokens:
    type:     rest
    resource: AppBundle\Controller\AuthTokenController

domaines:
    type:     rest
    resource: AppBundle\Controller\DomaineController

nelmio-api-doc:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /documentation