app:
    resource: "@AppBundle/Controller/"
    type:     annotation

users:
    type:     rest
    resource: AppBundle\Controller\UserController

auth-tokens:
    type:     rest
    resource: AppBundle\Controller\AuthTokenController